issues = Issues
new-issue = New Issue
issue-summary = Summary
issue-description = Description
issue-created-at = Created At
issue-authored-by = Added By
issue-error-internal-error = An error occurred saving to the database. Please try again. If you continue to have errors, ask your administrator to look in the logs.
issue-timeline = Issue Timeline
issue-edit-button = Update
edit-issue = Edit #{$issue_id}
save-issue = Save Issue
view-issue = Issue #{$issue_id}
issue-updated-summmary = Issue updated by {$user} at {$date}
issue-change-property = Property
issue-change-old-value = Previous
issue-change-new-value = Updated