issues = Issues
new-issue = New Issue
issue-summary = Summary
issue-description = Description
issue-created-at = Created At
issue-authored-by = Added By
issue-timeline = Issue Timeline
issue-edit-button = Update
issue-revision-comment = Comment
issue-project = Project
issue-project-none = No Project
edit-issue = Edit #{$issue_id}
save-issue = Save Issue
view-issue = Issue #{$issue_id}
issue-updated-summmary = Issue updated by {$user} at {$date}
issue-change-property = Property
issue-change-old-value = Previous
issue-change-new-value = Updated

issue-completed = Completed
issue-new = Ready